name = "claude-code-proxy"
main = "./src/index.ts"
compatibility_date = "2025-05-30"
compatibility_flags = ["nodejs_compat"]

[vars]
# DEBUG = "true"
# REASONING_MODEL = "z-ai/glm-4.5-air:free"
# COMPLETION_MODEL = "z-ai/glm-4.5-air:free"
# REASONING_EFFORT = "high"
